
workflows:
    react-native-android:
        name: React Native Android
        max_build_duration: 120
        instance_type: mac_pro
        environment:
            #  vars:
                # https://firebase.google.com/docs/cli#cli-ci-systems
                # FIREBASE_TOKEN: Encrypted(...) # <-- Put your encrypted Firebase App Distribution CI token here
                # CM_KEYSTORE: Encrypted(...) # <-- Put your encrypted keystore file here
                # CM_KEYSTORE_PASSWORD: Encrypted(...) # <-- Put your encrypted keystore password here
                # CM_KEY_ALIAS_PASSWORD: Encrypted(...) # <-- Put your encrypted keystore alias password here
                # CM_KEY_ALIAS_USERNAME: Encrypted(...) # <-- Put your encrypted keystore alias username here
             
            node: latest
        triggering:
          events:
              - push
              - tag
              - pull_request
          branch_patterns:
                - pattern: mobile
                  include: true
                  source: true
          scripts:
            - name: Install npm dependencies
              script: |
                npm install
            - name: Set Android SDK location
              script: |
                echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            # - name: Set up keystore
              # script: |
                    # echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
                    # cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
                    # storePassword=$CM_KEYSTORE_PASSWORD
                    # keyPassword=$CM_KEY_ALIAS_PASSWORD
                    # keyAlias=$CM_KEY_ALIAS_USERNAME
                    # storeFile=/tmp/keystore.keystore
                    # EOF
            - name: Build Android release
              script: |
                # build Android
                # cd android
                ./gradlew assembleRelease

        artifacts:
            - android/app/build/outputs/**/*.apk
        
        email:
          recipients:
            - stephen.olabode@nautilus.tech 