const ADD_PROFILE_PICTURE = 'addProfilePictures';
const DELETE_PROFILE_PICTURE = 'deleteProfilePictures';
const INIT_PROFILE_PICTURES = 'initProfilePictures';
const HYDRATE_PROFILE_PICTURES = 'hydrateProfilePictures';
const UPDATE_PROFILE_PICTURE_ALBUM_DETAILS = 'updateProfilePictureAlbumId';

const UPDATE_FB_TOKEN = 'updateFbToken';
const UPDATE_FB_CREDS = 'updateFbCreds';
const UPDATE_FB_READY = 'updateFbReady';
const HYDRATE_FB = 'HYDRATE_FB';

const UPDATE_USER_BIO = 'updateUserBio';
const UPDATE_USER_LOCATION = 'updateUserLocation';
const UPDATE_USER_QUESTION = 'updateUserQuestion';
const UPDATE_USER_ETHNICITY = 'updateUserEthnicity';
const UPDATE_USER_TWITTER = 'updateUserTwitter';
const UPDATE_USER_INSTAGRAM = 'updateUserInstagram';
const UPDATE_USER_RELIGION = 'updateUserReligion';
const UPDATE_USER_FLAG = 'updateUserFlag';
const UPDATE_USER_LIKE = 'updateUserLike';
const UPDATE_LOOKINGFOR_CRITERIA = 'updateLookingForCriteria';
const HYDRATE_USER = 'hydrateUser';

export {
  ADD_PROFILE_PICTURE,
  DELETE_PROFILE_PICTURE,
  INIT_PROFILE_PICTURES,
  HYDRATE_PROFILE_PICTURES,
  UPDATE_PROFILE_PICTURE_ALBUM_DETAILS,
  UPDATE_FB_TOKEN,
  UPDATE_FB_CREDS,
  UPDATE_FB_READY,
  HYDRATE_FB,
  UPDATE_USER_LOCATION,
  UPDATE_USER_BIO,
  UPDATE_USER_QUESTION,
  UPDATE_USER_TWITTER,
  UPDATE_USER_INSTAGRAM,
  UPDATE_USER_ETHNICITY,
  UPDATE_USER_RELIGION,
  UPDATE_LOOKINGFOR_CRITERIA,
  UPDATE_USER_FLAG,
  UPDATE_USER_LIKE,
  HYDRATE_USER,
};
