platform :ios, '9.0'
use_frameworks!

target 'trible' do
  pod 'SimpleAuth/Facebook'
  pod 'SimpleAuth/GoogleWeb'
  pod 'SimpleAuth/Twitter'
  pod 'SimpleAuth/Instagram'
  pod 'SimpleAuth/LinkedInWeb'


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'  ## or '3.0'
        end
    end
end

end

